name: DVAPI Automation with ZAP Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  dvapi-zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 2: Clone the DVAPI repository
      - name: Clone DVAPI
        uses: actions/checkout@v4
        with:
          repository: payatu/DVAPI  # Official DVAPI repo
          path: dvapi  # Clone into "dvapi" directory

      # Step 2: Build and Start DVAPI using Docker Compose
      - name: Start DVAPI
        working-directory: ./dvapi  # Navigate to DVAPI directory
        run: |
          docker-compose up -d --build  # Build and run DVAPI
          sleep 30  # Wait for DVAPI to initialize

      # Step 3: Run ZAP Scan against DVAPI (using host network)
      - name: Run ZAP Full Scan
        run: |
          docker run --network host \
            -v $(pwd):/zap/wrk/:rw \
            -t zaproxy/zap-stable zap-full-scan.py \
            -t http://127.0.0.1:3000 \  # DVAPI runs on port 3000
            -I

      # Step 4: Upload ZAP Report as Artifact
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dvapi-report
          path: zap-report.html
